/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Admin;

import java.awt.CardLayout;
import java.awt.Component;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.BrandCompany.PlannerProfile;
import model.BrandCompany.ProcurerDirectory;
import model.BrandCompany.ProcurerProfile;
import model.BrandCompany.ProductPlannerDirectory;
import model.BrandCompany.Requirement;
import model.Business.BrandEnterprise;
import model.Business.Business;
import model.Business.DesignEnterprise;
import model.Business.EnterpriseDirectory;
import model.Business.ProductionEnterprise;
import model.Business.RawMaterialEnterprise;
import model.DesignEnterprise.DesignerDirectory;
import model.DesignEnterprise.DesignerProfile;
import model.Personnel.AdminDirectory;
import model.Personnel.AdminProfile;
import model.Personnel.Person;
import model.Personnel.PersonDirectory;
import model.Production.InventoryManagerProfile;
import model.Production.InventoryOrganization;
import model.Production.ProductionManagerProfile;
import model.Production.ProductionOrganization;
import model.RawMaterialEnterprise.RawMaterialManager;
import model.UserAccountManagement.UserAccount;
import model.UserAccountManagement.UserAccountDirectory;
import ui.DesignerRole.ManageRequirementsTaskJPanel;

/**
 *
 * @author qiaohui
 */
public class AddAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageUserAccountJPanel
     */
    JPanel mainWorkArea;
    Business business;
    AdminProfile adminProfile;
    
    
    
    public AddAccountJPanel(Business business, JPanel mainWorkArea, AdminProfile adminProfile) {
        this.mainWorkArea = mainWorkArea;
        this.business = business;
        this.adminProfile = adminProfile;
        initComponents();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        AddButton = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        txtMName = new javax.swing.JTextField();
        lblName4 = new javax.swing.JLabel();
        txtCName = new javax.swing.JTextField();
        lblName1 = new javax.swing.JLabel();
        txtpass = new javax.swing.JTextField();
        lblName2 = new javax.swing.JLabel();
        txtp = new javax.swing.JTextField();
        lblName3 = new javax.swing.JLabel();
        cmbaccounttp = new javax.swing.JComboBox<>();

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        jLabel1.setText("Add  Account");

        AddButton.setText("Save Account Information");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        btnBack.setText(">>Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblName.setText("Username :");

        lblName4.setText("Company Name：");

        lblName1.setText("Password:");

        txtpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpassActionPerformed(evt);
            }
        });

        lblName2.setText("Person Name:");

        txtp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpActionPerformed(evt);
            }
        });

        lblName3.setText("Account Type:");

        cmbaccounttp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Procurer", "Planner", "Designer", "Raw Material Manager", "Inventory Manager", "Production Manager", " ", " " }));
        cmbaccounttp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbaccounttpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(414, 414, 414)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(251, 251, 251)
                                .addComponent(lblName1)
                                .addGap(40, 40, 40))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblName3)
                                    .addComponent(lblName2))
                                .addGap(30, 30, 30)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtpass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                            .addComponent(txtp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                            .addComponent(cmbaccounttp, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblName4)
                            .addComponent(lblName))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMName, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(381, 381, 381)
                        .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(358, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(btnBack)
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName4))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName1)
                    .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName2)
                    .addComponent(txtp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName3)
                    .addComponent(cmbaccounttp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(AddButton)
                .addContainerGap(206, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        mainWorkArea.remove(this);
        Component[] components = mainWorkArea.getComponents();
        Component component = components[components.length -1];
        ManageUserAccountJPanel manageUserAccountJPanel = (ManageUserAccountJPanel)component;
        manageUserAccountJPanel.populatePersonDirectoryTable();
        
        
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.previous(mainWorkArea);
    }//GEN-LAST:event_btnBackActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        // TODO add your handling code here:
        String companyName = txtCName.getText();
        String uername = txtMName.getText();
        String password = txtpass.getText();
        String profname = txtp.getText();
        
        
        //check the string if it is null
        if(companyName.equals("") || uername.equals("") || password.equals("") || profname.equals("")){
            JOptionPane.showMessageDialog(null, "Please add full information !!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        PersonDirectory personDirectory=business.getPersonDirectory();
        UserAccountDirectory useAccountDirectory=business.getUserAccountDirectory();
        Person p = personDirectory.newPerson(profname);
        String[] names = {"Kendall", "Kylie", "Kim", "Kris", "Khourteny"};
        Random r = new Random();
        String name = names[r.nextInt(names.length)];
        Person p2 = personDirectory.newPerson(name);
        String type = (String) cmbaccounttp.getSelectedItem();
               
        EnterpriseDirectory enterpriseDirectory =business.getEnterpriseDirectory();
        BrandEnterprise brandEnterprise= enterpriseDirectory.addBrandEnterprise(companyName);
        DesignEnterprise designEnterprise= enterpriseDirectory.addDesignEnterprise(companyName);
        RawMaterialEnterprise rawMaterialEnterprise=enterpriseDirectory.addRawMaterialEnterprise(companyName);


        
        switch (type) {
            case "Admin":
                AdminDirectory addirectory=business.getAdminDirectory();
                AdminProfile profile=addirectory.newEmployeeProfile(p);
                UserAccount us=useAccountDirectory.newUserAccount(profile, uername, password,companyName);
                JOptionPane.showMessageDialog(null, "Added Account Successfully!!", "Info", JOptionPane.INFORMATION_MESSAGE);
                break;
            case "Procurer":
                ProcurerDirectory prurerDirectory=brandEnterprise.getProcurementOrganization().getProcurerDirectory();
                ProcurerProfile profile1=prurerDirectory.newProcurerProfile(p);
                UserAccount us1=useAccountDirectory.newUserAccount(profile1, uername, password,companyName);
                JOptionPane.showMessageDialog(null, "Added Account Successfully!!", "Info", JOptionPane.INFORMATION_MESSAGE);
                break;
            case "Planner":
                ProductPlannerDirectory plannerDirectory=brandEnterprise.getProductPlanningOrganization().getPlannerDirectory();
                PlannerProfile profile2=plannerDirectory.addNewPlanner(p);
                UserAccount us2=useAccountDirectory.newUserAccount(profile2, uername, password,companyName);
                JOptionPane.showMessageDialog(null, "Added Account Successfully!!", "Info", JOptionPane.INFORMATION_MESSAGE);
                break;
            case "Designer":
                DesignerDirectory designerDirectory = designEnterprise.getDesignOrganization().getDesignerDirectory();
                DesignerProfile profile3 = designerDirectory.addANewDesignerProfile(p, 100);
                UserAccount us3=useAccountDirectory.newUserAccount(profile3, uername, password,companyName);
                JOptionPane.showMessageDialog(null, "Added Account Successfully!!", "Info", JOptionPane.INFORMATION_MESSAGE);

                break;
            case "Raw Material Manager":
                rawMaterialEnterprise.getRawMaterialManageOrganization().addRawMaterialManager(p);
                RawMaterialManager profile4= rawMaterialEnterprise.getRawMaterialManageOrganization().getRawMaterialManager();
                UserAccount us4=useAccountDirectory.newUserAccount(profile4, uername, password,companyName); 
                JOptionPane.showMessageDialog(null, "Added Account Successfully!!", "Info", JOptionPane.INFORMATION_MESSAGE);
                break;
            case "Production Manager":
                ProductionEnterprise productionEnterprise1= enterpriseDirectory.addProductionEnterprise(companyName, p2, p);
                ProductionOrganization productionOrganization = productionEnterprise1.getProductionOrganization();
                ProductionManagerProfile pmp = productionOrganization.getProductionManagerProfile();
                UserAccount us5=useAccountDirectory.newUserAccount(pmp, uername, password,companyName); 
                JOptionPane.showMessageDialog(null, "Added Account Successfully!!", "Info", JOptionPane.INFORMATION_MESSAGE);
                break;
            case "Inventory Manager":
                ProductionEnterprise productionEnterprise2=enterpriseDirectory.addProductionEnterprise(companyName, p,p2);
                InventoryOrganization inventoryOrganization = productionEnterprise2.getInventoryOrganization();
                InventoryManagerProfile imp = inventoryOrganization.getInventoryManagerProfile();
                UserAccount us6=useAccountDirectory.newUserAccount(imp, uername, password,companyName);
                JOptionPane.showMessageDialog(null, "Added Account Successfully!!", "Info", JOptionPane.INFORMATION_MESSAGE);
                break;
            default:
                break;
        }
        

        
        
        
        txtCName.setText(" ");
        txtMName.setText(" ");
        txtpass.setText(" ");
        txtp.setText(" ");
    
        
    }//GEN-LAST:event_AddButtonActionPerformed

    private void txtpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpassActionPerformed

    private void txtpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpActionPerformed

    private void cmbaccounttpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbaccounttpActionPerformed
        // TODO add your handling code here:

//        if (cmbaccounttp.getSelectedItem()==null) {
//            return;
//        }
//        String s=(String)cmbaccounttp.getSelectedItem();
//        selectedRawmaterial=selectedRawMaterialEnterprise.getRawMaterialDirectory().findRawMateiral(s);
//        if(selectedRawmaterial!=null) {
//            lblMaterialCost.setText(String.valueOf(selectedRawmaterial.getPrice()));
//        }
//        try{
//            lblTotalCost.setText(String.valueOf(selectedRawmaterial.getPrice()+selectdProductionmode.getModePrice()+selectedDesigner.getDefaultDesignPricing()));
//
//        }catch(Exception e){
//            return;
//        }
    }//GEN-LAST:event_cmbaccounttpActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox<String> cmbaccounttp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblName2;
    private javax.swing.JLabel lblName3;
    private javax.swing.JLabel lblName4;
    private javax.swing.JTextField txtCName;
    private javax.swing.JTextField txtMName;
    private javax.swing.JTextField txtp;
    private javax.swing.JTextField txtpass;
    // End of variables declaration//GEN-END:variables


    
}
