package ui;


import Business.ConfigureABusiness;
import Department.Department;
import Profiles.EmployeeProfile;
import Profiles.FacultyProfile;
import Profiles.Profile;
import Profiles.StudentProfile;
import UI.WorkAreas.AdminRole.AdminRoleWorkAreaJPanel;
import UI.WorkAreas.FacultyRole.FacultyWorkAreaJPanel;
import UI.WorkAreas.StudentRole.StudentWorkAreaJPanel;
import UserAccounts.UserAccount;
import UserAccounts.UserAccountDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.BrandCompany.Procurer;
import model.BrandCompany.RequirementsPlanner;
import model.Personnel.Profile;
import model.UserAccountManagement.UserAccount;
import model.UserAccountManagement.UserAccountDirectory;
import ui.BrandCompany.Procurer.ProcurerWorkAreaJPanel;
import ui.BrandCompany.ProductPlanner.PlannerWorkAreaJPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author qiaohui
 */
public class LoginJPanel1 extends javax.swing.JPanel {

    Department business;
    JPanel cardSequencePanel;
    
    public LoginJPanel1(JPanel cardSequencePanel,Department business) {
        initComponents();
        this.business=business;
        this.cardSequencePanel=cardSequencePanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogin = new javax.swing.JButton();
        lblUserAccount = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        txtUserName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        lblUserAccount.setText("User Account");

        jLabel2.setText("Password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(206, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(lblUserAccount))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUserName)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(btnLogin)))
                .addGap(196, 196, 196))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserAccount)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(btnLogin)
                .addContainerGap(190, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String un = txtUserName.getText();
        String pw = txtPassword.getText();

        UserAccountDirectory uad = business.getUserAccountDirectory();
        UserAccount useraccount = uad.AuthenticateUser(un, pw);
        if (useraccount == null) {
            JOptionPane.showMessageDialog(this, "Please input your account");
        }
        ProcurerWorkAreaJPanel procurerWorkAreajpanel;
        PlannerWorkAreaJPanel PlannerWorkAreaJpanel;
        String r = useraccount.getRole();
        Profile profile = useraccount.getAssociatedPersonProfile();

        if (profile instanceof Procurer) {
            Procurer p=(Procurer)profile;
            ProcurerWorkAreaJPanel pp= new ProcurerWorkAreaJPanel(business, p,cardSequencePanel);
            cardSequencePanel.removeAll();
            cardSequencePanel.add("Procurer", pp);
            CardLayout layout =(CardLayout)cardSequencePanel.getLayout();
            layout.next(cardSequencePanel);

        }

         if (profile instanceof RequirementsPlanner) {
            RequirementsPlanner spp = (RequirementsPlanner) profile;
            PlannerWorkAreaJPanel ppp= new PlannerWorkAreaJPanel(business, spp, cardSequencePanel);
            cardSequencePanel.removeAll();
            cardSequencePanel.add("Planner", ppp);
            CardLayout layout =(CardLayout)cardSequencePanel.getLayout();
            layout.next(cardSequencePanel);

        }

//        if (!(profile instanceof FacultyProfile)) {
//        } else {
//            FacultyProfile fp = (FacultyProfile) profile;
//            facultyworkarea = new FacultyWorkAreaJPanel(business, fp,cardSequencePanel);
//            cardSequencePanel.removeAll();
//            cardSequencePanel.add("faculty", facultyworkarea);
//            CardLayout layout =(CardLayout)cardSequencePanel.getLayout();
//            layout.next(cardSequencePanel);
//        }
    }//GEN-LAST:event_btnLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblUserAccount;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
