/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.BrandCompany.Planner;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.BrandCompany.PlannerProfile;
import model.Business.Business;
import model.Business.DesignEnterprise;
import model.Business.Enterprise;
import model.Business.ProductionEnterprise;
import model.Business.RawMaterialEnterprise;
import model.DesignEnterprise.DesignerProfile;
import model.DesignEnterprise.Style;
import model.Production.ProductionMode;
import model.RawMaterialEnterprise.RawMaterial;
import java.lang.String;
import model.BrandCompany.Requirement;
import model.BrandCompany.RequirementsDirectory;
import model.Business.BrandEnterprise;
import model.DesignEnterprise.Color;
import model.Production.InventoryManagerProfile;
import model.Production.ProductionManagerProfile;
import model.Production.ProductionOrder;
import model.Production.ProductionOrderDirectory;
import model.Production.ProductionOrganization;
import model.RawMaterialEnterprise.RawMaterialOrder;
import model.RawMaterialEnterprise.RawMaterialOrderDirectory;

/**
 *
 * @author qiaohui
 */
public class NewRequirementJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewRequirementJPanel
     */
    PlannerProfile plannerProfile;
    Business business;
    JPanel plannerWorkArea;
    BrandEnterprise brandEnterprise;
    RawMaterialEnterprise selectedRawMaterialEnterprise=null;
    RawMaterial selectedRawmaterial=null;
    ProductionEnterprise selectdProductionEnterprise=null;
    ProductionMode selectdProductionmode=null;
    DesignEnterprise selectedDesignEnterprise=null;
    DesignerProfile selectedDesigner=null;
    Style selectedStyle=null;
    Color selectedColor=null;

    
    public NewRequirementJPanel(Business business, PlannerProfile requirementPlanner, JPanel PlannerWorkArea,BrandEnterprise brandEnterprise) {
        initComponents();
        this.plannerProfile=requirementPlanner;
        this.business=business;
        this.plannerWorkArea=PlannerWorkArea;
        this.brandEnterprise=brandEnterprise;
        populateRawMaterialCompanyCombo();
        populateRawMaterialCombp();
        populateProductionCompanyCombo();
        populateProductionModeCombo();
        populateDesignCompanyCombo();
        populateDesginerCombp();
        populateDesignStyleCombo();
        populateDesignColorCombo();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbProductionMode = new javax.swing.JComboBox<>();
        cmbColor = new javax.swing.JComboBox<>();
        lblDesignStyle = new javax.swing.JLabel();
        lblRequirementID = new javax.swing.JLabel();
        CreateRerquirement = new javax.swing.JButton();
        lblRawMaterialpCost = new javax.swing.JLabel();
        cmbRawMaterial = new javax.swing.JComboBox<>();
        cmbDesignStyle = new javax.swing.JComboBox<>();
        lblProductionMode = new javax.swing.JLabel();
        lblColor = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblPicture = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblRawMaterial = new javax.swing.JLabel();
        lblModeCost = new javax.swing.JLabel();
        lblDesignFee = new javax.swing.JLabel();
        txtRequirementID = new javax.swing.JTextField();
        lblDeadline = new javax.swing.JLabel();
        txtDeadLine = new javax.swing.JTextField();
        lblRawMaterialCompany = new javax.swing.JLabel();
        cmbRawMaterialCompany = new javax.swing.JComboBox<>();
        lblProductionCompany = new javax.swing.JLabel();
        cmbProductionCompany = new javax.swing.JComboBox<>();
        lblDesignCompany = new javax.swing.JLabel();
        cmbDesignCompany = new javax.swing.JComboBox<>();
        lblDesignStyle1 = new javax.swing.JLabel();
        cmbDesigner = new javax.swing.JComboBox<>();
        lblTotalCost = new javax.swing.JLabel();
        lblMaterialCost = new javax.swing.JLabel();
        lblProductionModeCost1 = new javax.swing.JLabel();
        lblDesignCost = new javax.swing.JLabel();
        lblDeadline2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbProductionMode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbProductionMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProductionModeActionPerformed(evt);
            }
        });
        add(cmbProductionMode, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 226, 146, -1));

        cmbColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbColorActionPerformed(evt);
            }
        });
        add(cmbColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 364, 146, -1));

        lblDesignStyle.setText("Designe Style");
        add(lblDesignStyle, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 329, 146, 29));

        lblRequirementID.setText("RequirementID");
        add(lblRequirementID, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 110, 146, -1));

        CreateRerquirement.setText("Create Requirement");
        CreateRerquirement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateRerquirementActionPerformed(evt);
            }
        });
        add(CreateRerquirement, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 561, -1, -1));

        lblRawMaterialpCost.setText("Raw Material Cost:");
        add(lblRawMaterialpCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 171, 146, -1));

        cmbRawMaterial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbRawMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRawMaterialActionPerformed(evt);
            }
        });
        add(cmbRawMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 168, 146, -1));

        cmbDesignStyle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbDesignStyle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDesignStyleActionPerformed(evt);
            }
        });
        add(cmbDesignStyle, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 332, 146, -1));

        lblProductionMode.setText("Product Mode");
        add(lblProductionMode, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 229, 146, -1));

        lblColor.setText("Color ");
        add(lblColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 370, 146, -1));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setText("Creat New Reuirement");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 68, -1, -1));

        btnBack.setText(">>Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 54, -1, -1));

        lblPicture.setText("Renderings");
        add(lblPicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 461, 268, 37));

        jLabel8.setText("Picture is Here:*******");
        jLabel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 504, 176, 124));

        lblRawMaterial.setText("Raw Material");
        add(lblRawMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 171, -1, -1));

        lblModeCost.setText("<Cost>");
        add(lblModeCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(651, 226, -1, 23));

        lblDesignFee.setText("Design Fee:");
        add(lblDesignFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 299, -1, 23));

        txtRequirementID.setEnabled(false);
        txtRequirementID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRequirementIDActionPerformed(evt);
            }
        });
        add(txtRequirementID, new org.netbeans.lib.awtextra.AbsoluteConstraints(-670, -520, 146, -1));

        lblDeadline.setText("Deadline ");
        add(lblDeadline, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 402, -1, -1));

        txtDeadLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeadLineActionPerformed(evt);
            }
        });
        add(txtDeadLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 399, 146, -1));

        lblRawMaterialCompany.setText("Raw Material Company");
        add(lblRawMaterialCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 142, 170, -1));

        cmbRawMaterialCompany.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbRawMaterialCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRawMaterialCompanyActionPerformed(evt);
            }
        });
        add(cmbRawMaterialCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 139, 436, -1));

        lblProductionCompany.setText("Production Company");
        add(lblProductionCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 200, 170, -1));

        cmbProductionCompany.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbProductionCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProductionCompanyActionPerformed(evt);
            }
        });
        add(cmbProductionCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 197, 436, -1));

        lblDesignCompany.setText("Design Company");
        add(lblDesignCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 264, 170, -1));

        cmbDesignCompany.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbDesignCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDesignCompanyActionPerformed(evt);
            }
        });
        add(cmbDesignCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 261, 436, -1));

        lblDesignStyle1.setText("Designer");
        add(lblDesignStyle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 296, 80, 29));

        cmbDesigner.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbDesigner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDesignerActionPerformed(evt);
            }
        });
        add(cmbDesigner, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 299, 146, -1));

        lblTotalCost.setText("<Total Price >");
        add(lblTotalCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 440, -1, -1));

        lblMaterialCost.setText("< Cost>");
        add(lblMaterialCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(647, 171, 76, -1));

        lblProductionModeCost1.setText("Production Cost:");
        add(lblProductionModeCost1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, -1, 23));

        lblDesignCost.setText("<Cost>");
        add(lblDesignCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(661, 299, -1, 23));

        lblDeadline2.setText("Total Price ");
        add(lblDeadline2, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 440, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void cmbProductionModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProductionModeActionPerformed
        // TODO add your handling code here:
        if (cmbProductionMode.getSelectedItem()==null) {
            return;
        }
        String s=(String)cmbProductionMode.getSelectedItem();
        selectdProductionmode=selectdProductionEnterprise.getProductionOrganization().findProductionMode(s);
        if(selectdProductionmode!=null) {
            lblModeCost.setText(String.valueOf(selectdProductionmode.getModePrice()));
        }
        try{
            lblTotalCost.setText(String.valueOf(selectedRawmaterial.getPrice()+selectdProductionmode.getModePrice()+selectedDesigner.getDefaultDesignPricing()));

        }catch(Exception e){
            return;
        }
    }//GEN-LAST:event_cmbProductionModeActionPerformed

    private void txtRequirementIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRequirementIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRequirementIDActionPerformed

    private void txtDeadLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeadLineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeadLineActionPerformed

    private void cmbDesignerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDesignerActionPerformed
        // TODO add your handling code here:
        if (cmbDesigner.getSelectedItem()==null) {
            return;
        }
        String s=(String)cmbDesigner.getSelectedItem();
        selectedDesigner=selectedDesignEnterprise.getDesignOrganization().getDesignerDirectory().findDesignerProfile(s);
        if(selectedDesigner!=null) {
            lblDesignCost.setText(String.valueOf(selectedDesigner.getDefaultDesignPricing()));      
        }
        try{
            lblTotalCost.setText(String.valueOf(selectedRawmaterial.getPrice()+selectdProductionmode.getModePrice()+selectedDesigner.getDefaultDesignPricing()));

        }catch(Exception e){
            return;
        }
    }//GEN-LAST:event_cmbDesignerActionPerformed

    private void cmbRawMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRawMaterialActionPerformed
        // TODO add your handling code here:
        
         if (cmbRawMaterial.getSelectedItem()==null) {
            return;
        }
        String s=(String)cmbRawMaterial.getSelectedItem();
        selectedRawmaterial=selectedRawMaterialEnterprise.getRawMaterialDirectory().findRawMateiral(s);
        if(selectedRawmaterial!=null) {
            lblMaterialCost.setText(String.valueOf(selectedRawmaterial.getPrice()));
        }
        try{
            lblTotalCost.setText(String.valueOf(selectedRawmaterial.getPrice()+selectdProductionmode.getModePrice()+selectedDesigner.getDefaultDesignPricing()));

        }catch(Exception e){
            return;
        }
    
    }//GEN-LAST:event_cmbRawMaterialActionPerformed

    private void cmbDesignStyleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDesignStyleActionPerformed
        // TODO add your handling code here:
        if (cmbDesignStyle.getSelectedItem()==null) {
            return;
        }
        String s=(String)cmbDesignStyle.getSelectedItem();
        selectedStyle=selectedDesignEnterprise.getStyleDirectory().findStyle(s);
    }//GEN-LAST:event_cmbDesignStyleActionPerformed

    private void CreateRerquirementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateRerquirementActionPerformed
        // TODO add your handling code here:
        RequirementsDirectory requirementsdirectory=brandEnterprise.getProductPlanningOrganization().getRequirementDirectory();
        Requirement requirement=requirementsdirectory.addANewRrequirement(selectedRawmaterial, selectedDesigner, selectdProductionmode, plannerProfile, selectedStyle,selectedColor);
        requirement.setDeadline(txtDeadLine.getText());
        txtRequirementID.setText(requirement.getRequirementID());
       JOptionPane.showMessageDialog(this, "Requirement successfully added", "Information", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_CreateRerquirementActionPerformed

    private void cmbRawMaterialCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRawMaterialCompanyActionPerformed
        // TODO add your handling code here:
        if (cmbRawMaterialCompany.getSelectedItem()==null) {
            return;
        }
        String s=(String)cmbRawMaterialCompany.getSelectedItem();
        selectedRawMaterialEnterprise = business.getEnterpriseDirectory().getRawMaterialEnterprise(s);
        
    }//GEN-LAST:event_cmbRawMaterialCompanyActionPerformed

    private void cmbProductionCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProductionCompanyActionPerformed
        // TODO add your handling code here:
        if (cmbProductionCompany.getSelectedItem()==null) {
            return;
        }
        String s=(String)cmbProductionCompany.getSelectedItem();
        selectdProductionEnterprise = business.getEnterpriseDirectory().getProductionEnterprise(s);
        
    }//GEN-LAST:event_cmbProductionCompanyActionPerformed

    private void cmbDesignCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDesignCompanyActionPerformed
        // TODO add your handling code here:
        if (cmbDesignCompany.getSelectedItem()==null) {
            return;
        }
        String s=(String)cmbDesignCompany.getSelectedItem();
        selectedDesignEnterprise = business.getEnterpriseDirectory().getDesignEnterprise(s);
        
//        populateDesginerCombp();
//        populateDesignStyleCombo();
        
    }//GEN-LAST:event_cmbDesignCompanyActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        plannerWorkArea.remove(this);
        CardLayout layout = (CardLayout) plannerWorkArea.getLayout();
        layout.previous(plannerWorkArea);
    }//GEN-LAST:event_btnBackActionPerformed

    private void cmbColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbColorActionPerformed
        // TODO add your handling code here:
        if (cmbColor.getSelectedItem()==null) {
            return;
        }
        String s=(String)cmbColor.getSelectedItem();
        selectedColor=selectedDesignEnterprise.getColorDirectory().findColor(s);
    }//GEN-LAST:event_cmbColorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateRerquirement;
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox<String> cmbColor;
    private javax.swing.JComboBox<String> cmbDesignCompany;
    private javax.swing.JComboBox<String> cmbDesignStyle;
    private javax.swing.JComboBox<String> cmbDesigner;
    private javax.swing.JComboBox<String> cmbProductionCompany;
    private javax.swing.JComboBox<String> cmbProductionMode;
    private javax.swing.JComboBox<String> cmbRawMaterial;
    private javax.swing.JComboBox<String> cmbRawMaterialCompany;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblDeadline;
    private javax.swing.JLabel lblDeadline2;
    private javax.swing.JLabel lblDesignCompany;
    private javax.swing.JLabel lblDesignCost;
    private javax.swing.JLabel lblDesignFee;
    private javax.swing.JLabel lblDesignStyle;
    private javax.swing.JLabel lblDesignStyle1;
    private javax.swing.JLabel lblMaterialCost;
    private javax.swing.JLabel lblModeCost;
    private javax.swing.JLabel lblPicture;
    private javax.swing.JLabel lblProductionCompany;
    private javax.swing.JLabel lblProductionMode;
    private javax.swing.JLabel lblProductionModeCost1;
    private javax.swing.JLabel lblRawMaterial;
    private javax.swing.JLabel lblRawMaterialCompany;
    private javax.swing.JLabel lblRawMaterialpCost;
    private javax.swing.JLabel lblRequirementID;
    private javax.swing.JLabel lblTotalCost;
    private javax.swing.JTextField txtDeadLine;
    private javax.swing.JTextField txtRequirementID;
    // End of variables declaration//GEN-END:variables

    private void populateRawMaterialCompanyCombo() {
        cmbRawMaterialCompany.removeAllItems();
        for(RawMaterialEnterprise enterprise:business.getEnterpriseDirectory().getRawMaterialEnterpriseList()){
            cmbRawMaterialCompany.addItem(enterprise.toString());
        }
//        for(Enterprise enterprise:business.getEnterpriseDirectory().findRawMaterialEnterpriseList()){
//            cmbRawMaterialCompany.addItem(enterprise);
//        }
    }

    private void populateProductionCompanyCombo() {
        cmbProductionCompany.removeAllItems();
        for(ProductionEnterprise enterprise:business.getEnterpriseDirectory().getProductionEnterpriseList()){
            cmbProductionCompany.addItem(enterprise.toString());
        }  
//        for(Enterprise enterprise:business.getEnterpriseDirectory().findProductionEnterpriseList()){
//            cmbProductionCompany.addItem(enterprise);
//        }
    }

    private void populateDesignCompanyCombo() {
        cmbDesignCompany.removeAllItems();
        for(DesignEnterprise enterprise:business.getEnterpriseDirectory().getDesignEnterpriseList()){
            cmbDesignCompany.addItem(enterprise.toString());
        }
        
    }
    
    private void populateDesignStyleCombo() {
        cmbDesignStyle.removeAllItems();
        //DesignEnterprise selectedRawMaterialEnterprise=(DesignEnterprise)cmbDesignCompany.getSelectedItem();
//        String s=(String)cmbDesignCompany.getSelectedItem();
//        DesignEnterprise selectedEnterprise=business.getEnterpriseDirectory().getDesignEnterprise(s);
        for(Style style:selectedDesignEnterprise.getStyleDirectory().getStyleDirectory()){
            cmbDesignStyle.addItem(style.toString());
        }    
    }

    private void populateRawMaterialCombp() {
        cmbRawMaterial.removeAllItems();
        //RawMaterialEnterprise selectedRawMaterialEnterprise=(RawMaterialEnterprise)cmbRawMaterialCompany.getSelectedItem();
        for(RawMaterial rawmaterial:selectedRawMaterialEnterprise.getRawMaterialDirectory().getRawMaterialDirectory()){
            cmbRawMaterial.addItem(rawmaterial.toString());
        }
    }

    private void populateProductionModeCombo() {
        cmbProductionMode.removeAllItems();
//        String s=(String)cmbProductionCompany.getSelectedItem();
//        ProductionEnterprise selectedEnterprise=business.getEnterpriseDirectory().getProductionEnterprise(s);
        //ProductionEnterprise productionenterprise=(ProductionEnterprise)cmbProductionCompany.getSelectedItem();
        for(ProductionMode productionmode:selectdProductionEnterprise.getProductionOrganization().getProductionModeDirectory().getProductionModeList()){
            cmbProductionMode.addItem(productionmode.toString());
        }
    }

    private void populateDesginerCombp() {
        cmbDesigner.removeAllItems();
//        String s=(String)cmbDesignCompany.getSelectedItem();
//        DesignEnterprise selectedEnterprise=business.getEnterpriseDirectory().getDesignEnterprise(s);
        for(DesignerProfile designer: selectedDesignEnterprise.getDesignOrganization().getDesignerDirectory().getDesignerProfileList()){
            cmbDesigner.addItem(designer.toString());
        }
    }

    private void populateDesignColorCombo() {
        cmbColor.removeAllItems();
        //DesignEnterprise selectedRawMaterialEnterprise=(DesignEnterprise)cmbDesignCompany.getSelectedItem();
//        String s=(String)cmbDesignCompany.getSelectedItem();
//        DesignEnterprise selectedEnterprise=business.getEnterpriseDirectory().getDesignEnterprise(s);
        for(Color color:selectedDesignEnterprise.getColorDirectory().getCorlorlist()){
            cmbColor.addItem(color.toString());
        } 
    }
    
    
    
    
}
