/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.BrandCompany.Planner;

import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;
import model.BrandCompany.PlannerProfile;
import model.Business.BrandEnterprise;
import model.Business.Business;
import ui.LoginJPanel;

/**
 *
 * @author qiaohui
 */
public class PlannerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form delivererWorkAreaJPanel
     */
    JPanel mainWorkArea;
    Business business;
    PlannerProfile requirementPlanner;
    BrandEnterprise brandEnterprise;
    
    
    public PlannerWorkAreaJPanel(Business business,PlannerProfile requirementPlanner, JPanel PlannerWorkArea, BrandEnterprise e) {
        this.mainWorkArea=PlannerWorkArea;
        this.requirementPlanner=requirementPlanner;
        this.business=business;
        this.brandEnterprise=e;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        RequirementManage = new javax.swing.JButton();
        NewRequirement = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        PlannerWorkArea = new javax.swing.JPanel();

        setBackground(new java.awt.Color(239, 223, 208));

        jPanel1.setBackground(new java.awt.Color(249, 239, 224));

        RequirementManage.setBackground(new java.awt.Color(123, 145, 128));
        RequirementManage.setText("Requirement Manage");
        RequirementManage.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        RequirementManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequirementManageActionPerformed(evt);
            }
        });

        NewRequirement.setBackground(new java.awt.Color(123, 145, 128));
        NewRequirement.setText("New Requirement ");
        NewRequirement.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        NewRequirement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewRequirementActionPerformed(evt);
            }
        });

        btnLogOut.setBackground(new java.awt.Color(123, 145, 128));
        btnLogOut.setText("Log out");
        btnLogOut.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(NewRequirement, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnLogOut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RequirementManage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(RequirementManage)
                .addGap(26, 26, 26)
                .addComponent(NewRequirement)
                .addGap(176, 176, 176)
                .addComponent(btnLogOut)
                .addContainerGap(203, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        PlannerWorkArea.setBackground(new java.awt.Color(249, 239, 224));
        PlannerWorkArea.setForeground(new java.awt.Color(51, 51, 51));
        PlannerWorkArea.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(PlannerWorkArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RequirementManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequirementManageActionPerformed
        // TODO add your handling code here:
        RequirementManagementJPanel aos = new RequirementManagementJPanel(business,requirementPlanner, PlannerWorkArea,brandEnterprise);
        PlannerWorkArea.add("Requirement Management", aos);
        CardLayout layout =(CardLayout)PlannerWorkArea.getLayout();
        layout.next(PlannerWorkArea); 
    }//GEN-LAST:event_RequirementManageActionPerformed

    private void NewRequirementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewRequirementActionPerformed
        // TODO add your handling code here:
        NewRequirementJPanel aos = new NewRequirementJPanel(business,requirementPlanner, PlannerWorkArea,brandEnterprise);
        PlannerWorkArea.add("Requirement Management", aos);
        CardLayout layout =(CardLayout)PlannerWorkArea.getLayout();
        layout.next(PlannerWorkArea);
    }//GEN-LAST:event_NewRequirementActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        mainWorkArea.remove(this);
        Component[] componentArray = mainWorkArea.getComponents();
        Component component = componentArray[componentArray.length - 1];
        LoginJPanel loginPanel = (LoginJPanel) component;
        loginPanel.populateEnterpriseTypeCombo();
        loginPanel.populateCompanyNameCombo();
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.previous(mainWorkArea);
    }//GEN-LAST:event_btnLogOutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NewRequirement;
    private javax.swing.JPanel PlannerWorkArea;
    private javax.swing.JButton RequirementManage;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
