/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.DesignerRole;

/**
 *
 * @author tianlyu
 */
public class ManageRequirementsTaskJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageRequirementsTask1JPanel
     */
    public ManageRequirementsTaskJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        addusersjButton = new javax.swing.JButton();
        manageusersjButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(236, 244, 251));

        Back.setText("<< Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Designer Work Area");

        addusersjButton.setBackground(new java.awt.Color(102, 153, 255));
        addusersjButton.setForeground(new java.awt.Color(255, 255, 255));
        addusersjButton.setText("Manage Requirements Task");
        addusersjButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addusersjButton.setMaximumSize(new java.awt.Dimension(200, 40));
        addusersjButton.setMinimumSize(new java.awt.Dimension(20, 20));
        addusersjButton.setPreferredSize(new java.awt.Dimension(240, 25));
        addusersjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addusersjButtonActionPerformed(evt);
            }
        });

        manageusersjButton2.setBackground(new java.awt.Color(102, 153, 255));
        manageusersjButton2.setForeground(new java.awt.Color(255, 255, 255));
        manageusersjButton2.setText("Check Performance");
        manageusersjButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        manageusersjButton2.setMaximumSize(new java.awt.Dimension(200, 40));
        manageusersjButton2.setMinimumSize(new java.awt.Dimension(20, 20));
        manageusersjButton2.setPreferredSize(new java.awt.Dimension(240, 25));
        manageusersjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageusersjButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addusersjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageusersjButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(268, 268, 268))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Back)
                .addGap(51, 51, 51)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(addusersjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(manageusersjButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(322, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        //        // TODO add your handling code here:
        //        CardSequencePanel.remove(this);
        //        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_BackActionPerformed

    private void addusersjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addusersjButtonActionPerformed
        // TODO add your handling code here:
        //        AddUsersJPanel aos = new AddUsersJPanel(business, CardSequencePanel);
        //        CardSequencePanel.add("Add Users", aos);
        //        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_addusersjButtonActionPerformed

    private void manageusersjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageusersjButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manageusersjButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton addusersjButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton manageusersjButton2;
    // End of variables declaration//GEN-END:variables
}
